import { X } from 'lucide-react';

type Pair = { key: string; value: string };

type Props = {
    // Accept unknown: pipelines edited externally (or generated by an AI / MCP)
    // can carry a non-conforming shape here, e.g. an object {k:v} instead of a
    // [{key,value}] array. Coerce rather than crash the whole panel (#93).
    value: unknown;
    onChange: (v: Pair[]) => void;
};

/** Coerce any stored value into the [{key,value}] shape the editor expects. */
function toPairs(value: unknown): Pair[] {
    if (Array.isArray(value)) {
        return value
            .filter((p): p is Record<string, unknown> => Boolean(p) && typeof p === 'object')
            .map(p => ({ key: String(p.key ?? ''), value: String(p.value ?? '') }));
    }
    if (value && typeof value === 'object') {
        // Plain object map { "Region": "Region" } -> one row per entry.
        return Object.entries(value as Record<string, unknown>).map(([k, v]) => ({
            key: k,
            value: v == null ? '' : String(v),
        }));
    }
    return [];
}

export function KeyValueField({ value, onChange }: Props) {
    const pairs = toPairs(value);

    const add = () => onChange([...pairs, { key: '', value: '' }]);
    const update = (i: number, patch: Partial<Pair>) =>
        onChange(pairs.map((p, idx) => (idx === i ? { ...p, ...patch } : p)));
    const remove = (i: number) => onChange(pairs.filter((_, idx) => idx !== i));

    return (
        <div className="field-kv">
            <div className="field-agg-toolbar">
                <span className="field-agg-count">
                    {pairs.length} entr{pairs.length === 1 ? 'y' : 'ies'}
                </span>
                <button type="button" className="schema-add" onClick={add}>
                    + Add
                </button>
            </div>
            {pairs.map((p, i) => (
                <div className="field-kv-row" key={i}>
                    <input
                        type="text"
                        className="schema-input"
                        value={p.key}
                        placeholder="key"
                        onChange={e => update(i, { key: e.target.value })}
                        spellCheck={false}
                    />
                    <input
                        type="text"
                        className="schema-input"
                        value={p.value}
                        placeholder="value"
                        onChange={e => update(i, { value: e.target.value })}
                        spellCheck={false}
                    />
                    <button
                        type="button"
                        className="schema-remove"
                        onClick={() => remove(i)}
                        aria-label="Remove"
                    >
                        <X size={12} />
                    </button>
                </div>
            ))}
        </div>
    );
}
